apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-restored
  namespace: ch04
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3
  resources:
    requests:
      storage: 4Gi
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: data-snap
