apiVersion: v1
kind: Namespace
metadata:
  name: mini-app
  labels:
    # PSA baseline で全 workload が動くことが卒業条件
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
