Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20220530.0.0"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 2
        vb.memory = "4096"
    end
    config.vm.synced_folder "./", "/vagrant"

    config.vm.define "controlplane01" do |server|
        server.vm.hostname = "controlplane01"
        server.vm.network "private_network", ip: "192.168.200.11", virtualbox__intnet: "mynetwork"
        server.vm.network "public_network", en0: "ens0: Ethernet"
        # server.vm.disk :disk, size: "15GB", primary: true
    end

    config.vm.define "worker01" do |server|
        server.vm.hostname = "worker01"
        server.vm.network "private_network", ip: "192.168.200.21", virtualbox__intnet: "mynetwork"
        server.vm.network "public_network", en0: "ens0: Ethernet"
        # server.vm.disk :disk, size: "15GB", primary: true
    end
end
