apiVersion: v1
kind: Namespace
metadata:
  name: ch06
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: ch06
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: c
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-pdb
  namespace: ch06
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: hello
